name: Other

on: [push]

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: Specification Document Compilation
    steps:
      - uses: actions/checkout@v1
      - name: Compilation
        uses: vinay0410/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: "tex/specification/specification.tex"
          push: "no"

      - name: Upload Specification
        uses: actions/upload-artifact@v1
        with:
          name: Specification.pdf
          path: tex/specification/specification.pdf

  convert-issues:
    runs-on: ubuntu-latest
    name: Convert TODOs to Github Issues
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@master"
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "# TODO"
          COMMENT_MARKER: "#"
        id: "todo"