name: Update Specification

on: [push]

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: Specification Document Compilation
    steps:
      - uses: actions/checkout@v1
      - name: Compilation
        uses: vinay0410/tectonic-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tex_path: "tex/documentation/documentation.tex"
          push: "no"
          
      - name: Upload Specification
        uses: actions/upload-artifact@v1
        with:
          name: documentation.pdf
          path: tex/documentation/documentation.pdf
